#!/usr/bin/env node
/**
 * Self-host the theme's Google Fonts.
 *
 * The theme declares three Google Fonts families (see theme-input.toml [fonts]):
 *   --font-sans: 'Noto Sans Display', Inter, sans-serif
 *   --font-mono: 'Noto Sans Mono', 'Google Sans Code', monospace
 *
 * Historically consumers had to load these themselves (a <link> to Google
 * Fonts). This script downloads the woff2 files into src/assets/fonts/ and emits
 * src/assets/fonts/fonts.css with @font-face rules pointing at the local files,
 * so the showcase app picks them up in dev and consumers can self-host by
 * importing '@smuit/smuit-theme/fonts.css'. src/assets/fonts/ ships in the
 * published package (see "files" in package.json), mirroring output.min.css.
 *
 * Variable fonts are fetched at their full weight (and, for Noto Sans Display,
 * width) ranges. Only the SUBSETS listed below are kept to keep the package lean.
 *
 * Downloads are cached: an existing woff2 of the right size is reused, so a
 * release does not fail when offline / rate-limited.
 *
 * Usage: node scripts/fetch-fonts.mjs   (FORCE=1 to re-download)
 */
import { mkdir, writeFile, stat } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT_DIR = join(ROOT, 'src', 'assets', 'fonts');
const FORCE = process.env.FORCE === '1' || process.env.FORCE === 'true';

// A real browser UA is required for the css2 API to return woff2 (vs ttf).
const UA =
	'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 ' +
	'(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

// Unicode subsets to keep. Noto/Google families ship many; latin + latin-ext
// cover Western European text. Add more here if needed (e.g. 'vietnamese').
const SUBSETS = ['latin', 'latin-ext'];

// `spec` is the css2 `family=` value: axes (alpha order) then ranges.
const FAMILIES = [
	{ name: 'Noto Sans Display', spec: 'Noto+Sans+Display:wdth,wght@62.5..100,100..900' },
	{ name: 'Noto Sans Mono', spec: 'Noto+Sans+Mono:wght@100..900' },
	{ name: 'Google Sans Code', spec: 'Google+Sans+Code:wght@300..800' }
];

const slug = (s) =>
	s
		.toLowerCase()
		.replace(/[^a-z0-9]+/g, '-')
		.replace(/^-|-$/g, '');

const fetchText = async (url) => {
	const res = await fetch(url, { headers: { 'User-Agent': UA } });
	if (!res.ok) throw new Error(`GET ${url} → ${res.status} ${res.statusText}`);
	return res.text();
};

const fileExists = async (p) => {
	try {
		const s = await stat(p);
		return s.isFile() && s.size > 0;
	} catch {
		return false;
	}
};

/** Parse css2 output into { subset, block, url } entries (one @font-face each). */
function parseFaces(css) {
	const faces = [];
	const re = /\/\*\s*([a-z0-9-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/gi;
	let m;
	while ((m = re.exec(css)) !== null) {
		const [, subset, block] = m;
		const url = block.match(/url\((https:\/\/[^)]+\.woff2)\)/i)?.[1];
		if (url) faces.push({ subset, block, url });
	}
	return faces;
}

async function main() {
	await mkdir(OUT_DIR, { recursive: true });

	const cssChunks = [];
	let downloaded = 0;
	let cached = 0;

	for (const family of FAMILIES) {
		const url = `https://fonts.googleapis.com/css2?family=${family.spec}&display=swap`;
		const css = await fetchText(url);
		const faces = parseFaces(css).filter((f) => SUBSETS.includes(f.subset));

		if (faces.length === 0) {
			throw new Error(
				`No @font-face for "${family.name}" in subsets [${SUBSETS.join(', ')}] — ` +
					`check the family spec or SUBSETS list.`
			);
		}

		for (const face of faces) {
			const fileName = `${slug(family.name)}-${face.subset}.woff2`;
			const filePath = join(OUT_DIR, fileName);

			if (!FORCE && (await fileExists(filePath))) {
				cached++;
			} else {
				const res = await fetch(face.url, { headers: { 'User-Agent': UA } });
				if (!res.ok) throw new Error(`GET ${face.url} → ${res.status}`);
				await writeFile(filePath, Buffer.from(await res.arrayBuffer()));
				downloaded++;
			}

			// Rewrite the remote url to the local file, keep the rest of the block.
			cssChunks.push(
				`/* ${family.name} — ${face.subset} */\n` +
					face.block.replace(/url\(https:\/\/[^)]+\.woff2\)/i, `url(./${fileName})`)
			);
		}
	}

	const header =
		'/* GENERATED by scripts/fetch-fonts.mjs — self-hosted Google Fonts for @smuit/smuit-theme.\n' +
		" * Import alongside the theme: @import '@smuit/smuit-theme/fonts.css';\n" +
		' */\n\n';
	await writeFile(join(OUT_DIR, 'fonts.css'), header + cssChunks.join('\n\n') + '\n');

	console.log(
		`fonts: ${downloaded} downloaded, ${cached} cached → ${join('src', 'assets', 'fonts')} ` +
			`(${cssChunks.length} faces across ${FAMILIES.length} families)`
	);
}

main().catch((err) => {
	console.error(`fetch-fonts failed: ${err.message}`);
	process.exit(1);
});
